version: '2'
services:
    jhipsterelastic-app:
        image: jhipsterelastic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterelastic-postgresql:5432/jhipsterElastic
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsterelastic-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterelastic-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterelastic-postgresql
    jhipsterelastic-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterelastic-elasticsearch
